{% set name = "python-simpleconf" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-simpleconf-{{ version }}.tar.gz
  sha256: 1700249e966532f11747a346c238672c01d87c8c437fa16525a124362093da50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry >=0.12
  run:
    - diot >=0.1,<0.2
    - python >=3.6,<4.0

test:
  imports:
    - simpleconf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/simpleconf
  summary: Simple configuration management with python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AhmedAliStats
